name: Deploy Miguer API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Build,Migrate & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/miguer/miguer-api/
            git pull
            /home/miguer/.cargo/bin/cargo build --release
            rm -rf miguer_api-cli
            cp target/release/miguer_api-cli miguer_api-cli
            /home/miguer/.nvm/versions/node/v22.15.0/bin/pm2 startOrReload ecosystem.config.js --update-env
